services:
  frontend:
    image: projekt_court_frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: localhost:8080
      NEXT_PUBLIC_ERROR_HOLD_TIME_IN_MS: 5000
    networks:
      - projekt_court

networks:
  projekt_court:
    driver: bridge